export const currencies = {
  USD: '$',
  EUR: '€',
  THB: '฿',
  MXN: '$',
  NGN: '₦',
  UAH: '₴',
  INR: '₹',
  PHP: '₱',
  VND: '₫',
  AUD: '$',
  JPY: '¥',
  CAD: '$',
  RUB: '₽',
  KRW: '₩',
  GBP: '£',
  IDR: 'Rp',
  HKD: 'HK$',
  CHF: 'CHF',
  MYR: 'RM',
  KES: 'KSh',
  PKR: '₨',
  DKK: 'kr',
  TZS: 'TSh',
  ZAR: 'R',
  PLN: 'zł',
  HTG: 'G',
  CZK: 'Kč',
  RON: 'lei',
  SEK: 'kr'
}

export const currencyIdsTab = [
  { value: 1, name: 'USD' },
  { value: 2, name: 'EUR' },
  { value: 3, name: 'THB' },
  { value: 4, name: 'MXN' },
  { value: 5, name: 'NGN' },
  { value: 6, name: 'UAH' },
  { value: 7, name: 'INR' },
  { value: 8, name: 'PHP' },
  { value: 9, name: 'VND' },
  { value: 10, name: 'AUD' },
  { value: 11, name: 'JPY' },
  { value: 12, name: 'CAD' },
  { value: 13, name: 'RUB' },
  { value: 14, name: 'KRW' },
  { value: 15, name: 'GBP' },
  { value: 16, name: 'IDR' },
  { value: 17, name: 'HKD' },
  { value: 18, name: 'CHF' },
  { value: 19, name: 'MYR' },
  { value: 20, name: 'KES' },
  { value: 21, name: 'PKR' },
  { value: 22, name: 'DKK' },
  { value: 23, name: 'TZS' },
  { value: 24, name: 'ZAR' },
  { value: 25, name: 'PLN' },
  { value: 26, name: 'HTG' },
  { value: 27, name: 'CZK' },
  { value: 28, name: 'RON' },
  { value: 29, name: 'SEK' }
]
